[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build",
  "ls -la dist"
]

[start]
cmd = "npm run start:prod:migrate"

[variables]
NODE_ENV = "production"