[phases.setup]
nixPkgs = ["nodejs_22", "python3"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm run start:prod:migrate"